-- vim.opt.completeopt = { "menuone", "noselect", "popup" }
--
-- local lsps = { -- Don't forget to add config in "./lsp/<server_name>.lua"!
--     "luals",
--     "clangd",
--     -- "haskellls",
--     "pyright",
-- }
--
-- for _, lsp in pairs(lsps) do
--     vim.lsp.enable(lsp)
-- end

-- for _, lsp in pairs(lsps) do
--     -- local setup = {}
--     vim.lsp.config(lsp, {
--         on_attach = function(client, bufnr)
--             vim.lsp.completion.enable(true, client.id, bufnr, {
--                 autotrigger = true,
--                 convert = function(item)
--                     return { abbr = item.label:gsub("%b()", "") }
--                 end,
--             })
--             vim.keymap.set("i", "<C-space>", vim.lsp.completion.get, { desc = "trigger autocompletion" })
--             print("Attached: " .. lsp)
--         end
--     })
--     vim.lsp.enable(lsp)
-- end

-- for _, lsp in pairs(lsps) do
--     -- local setup = {}
--     vim.lsp.enable(lsp){
--         on_attach = function(client, bufnr)
--             vim.lsp.completion.enable(true, client.id, bufnr, {
--                 autotrigger = true,
--                 convert = function(item)
--                     return { abbr = item.label:gsub("%b()", "") }
--                 end,
--             })
--             vim.keymap.set("i", "<C-space>", vim.lsp.completion.get, { desc = "trigger autocompletion" })
--         end
--     }
-- end

-- for _, lsp in pairs(lsps) do
--     -- local setup = {}
--     vim.lsp.start({
--         name = lsp,
--         on_attach = function(client, bufnr)
--             vim.lsp.completion.enable(true, client.id, bufnr, {
--                 autotrigger = true,
--                 convert = function(item)
--                     return { abbr = item.label:gsub('%b()', '') }
--                 end,
--             })
--         end,
--     })
--     -- vim.lsp.enable(lsp)
-- end
--
